//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthorsBook
    {
        public int AurthorId { get; set; }
        public string ISBN { get; set; }
        public int YearPublished { get; set; }
        public string Edition { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Book Book { get; set; }
    }
}
