//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string OrderType { get; set; }
        public System.DateTime RequiredDate { get; set; }
        public System.DateTime ShippingDate { get; set; }
        public int CustomerId { get; set; }
        public int EmployeeId { get; set; }
        public double Payment { get; set; }
        public int StatusOrderId { get; set; }
        public string ISBN { get; set; }
        public string QuantityOrdered { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual EmployeeEntity Employee { get; set; }
        public virtual StatusOrder StatusOrder { get; set; }
        public virtual Book Book { get; set; }
    }
}
